export const aboutCopy = {
  en: {
    lang: "en", title: "Our world", description: "KIKORA brings independent art, original characters and gaming culture into objects made to be part of everyday life. Discover our vision for artist-led collections.",
    eyebrow: "KIKORA / A WORLD WORTH COLLECTING", heroTitle: ["An artist’s world.", "A place in yours."],
    intro: ["We’re building a meeting place for artists and players.", "A place where original worlds move beyond the screen and become objects you can hold, live with and keep."], enter: "Explore our story",
    wraithAlt: "Blue Wraith-inspired concept study combining character art with the visual language of album covers", visualMark: ["WORLD", "IN PROGRESS."], visualStudy: "VISUAL STUDY / 001", visualNote: "Concept study · Not a released collaboration",
    beginning: "01 / THE BEGINNING", sharedPassion: "A shared connection", storyTitle: ["Some worlds stay with you", "long after you log off."],
    story: ["A character you’ve played for countless hours. An album that never leaves your rotation. An illustration that makes you stop scrolling. The work we love does more than look good. It reflects a part of who we are.", "That connection is where KIKORA begins. We want to bring the creative energy of anime, games, music and street culture into art you can live with. Your desk can hold more than equipment. It can hold a little of your history, your taste and your world."],
    beliefLabel: "02 / WHAT WE BELIEVE", beliefTitle: ["Three things", "every piece should carry."],
    beliefs: [
      { number: "01", label: "THE CREATOR", title: "The artist comes first.", body: "We want to know the person behind the style. An original character, a personal story or a world still waiting to be seen can be the beginning of a collection." },
      { number: "02", label: "THE EDITION", title: "More than a number.", body: "An edition should reward a closer look and make its artist, concept and release details clear. We see limited editions as a way to give a work the care it deserves. Quantities and release plans will be announced with each confirmed collection." },
      { number: "03", label: "THE EVERYDAY", title: "Keep what moves you close.", body: "A collection can live in a display case. It can also live within reach. At the start of a session, between matches or late into the night, art can be part of the time you actually spend." },
    ],
    reynaAlt: "Red and blue Reyna-inspired concept study exploring character art and album-cover composition", creatorVisualNote: "CONCEPT STUDY / Not a released collaboration",
    creatorLabel: "03 / MANY CREATORS. MANY WORLDS.", creatorTitle: ["The next chapter", "needs more voices."],
    creatorBody: ["We hope to work with independent illustrators and original-IP creators from cities across China. The ambition is to give each artist’s voice room to lead, so collectors can discover a world that feels like their own.", "There is no single style everyone has to follow. A world can be stark, vivid, strange or quietly intimate. What matters is that it belongs to the person creating it."],
    creatorStatus: "Artist collaboration program · In development", creatorAction: "Tell us about your work", mailSubject: "Artist collaboration / KIKORA",
    objectsLabel: "04 / ART TAKES FORM", objectsTitle: ["One world.", "More ways to keep it."], objectsBody: "We’re exploring three kinds of objects, bringing the image, the feel and the way you use them into the work itself.",
    objects: [
      { href: "/explore/glass", label: "01 / GLASS MOUSEPADS", title: "Glass mousepads", body: "A full canvas at the center of your desk.", action: "Explore the direction" },
      { href: "/explore/keycaps", label: "02 / KEYCAPS", title: "Art keycaps", body: "Character, color and composition, close at hand.", action: "Explore the direction" },
      { href: "/explore/metal", label: "03 / METAL CUSTOMS", title: "Metal customs", body: "New dimensions for the worlds we collect.", action: "See what’s taking shape" },
    ],
    invitationLabel: "THE STORY IS STILL BEING WRITTEN.", invitationTitle: ["Find your world.", "Keep a piece of it close."], invitationBody: ["Artist collaborations and limited-edition collections are in development.", "Follow the next idea, the next artist and the next piece as they take shape."], invitationAction: "Follow new editions",
  },
  ja: {
    lang: "ja", title: "KIKORA の世界", description: "作家が描く世界と、ゲームやアニメを愛する人の日常をつなぐ。KIKORA は、オリジナル IP と独自の表現から生まれるアートコレクションを構想しています。",
    eyebrow: "KIKORA / 好きな世界を、手元に", heroTitle: ["クリエイターの世界を、", "あなたのコレクションに。"],
    intro: ["作家の想像力と、プレイヤーの毎日が出会う場所へ。", "画面の中にあった世界を、触れられるかたちに。いつまでもそばに置きたくなる作品を目指しています。"], enter: "私たちの物語を読む",
    wraithAlt: "レイスを題材に、キャラクターアートとアルバムジャケットの表現を組み合わせた青いビジュアル研究", visualMark: ["新しい世界が、", "かたちになる。"], visualStudy: "ビジュアル研究 / 001", visualNote: "コンセプト研究・発売済みコラボ作品ではありません",
    beginning: "01 / 物語のはじまり", sharedPassion: "同じ「好き」から", storyTitle: ["ゲームを閉じたあとも、", "離れたくない世界がある。"],
    story: ["何度も一緒に戦ったキャラクター。繰り返し聴いてきたアルバム。思わず手を止めて見入った一枚の絵。ただ美しいだけではない、自分のどこかと響き合うものに、私たちは惹かれます。", "KIKORA の出発点は、その気持ちです。アニメ、ゲーム、音楽、ストリートカルチャーから生まれる表現を、毎日に置けるアートへ。デスクは機材を並べる場所であると同時に、好みや記憶、自分らしさを集める場所にもなれると考えています。"],
    beliefLabel: "02 / 大切にしたいこと", beliefTitle: ["ひとつの作品に、", "欠かせない3つのこと。"],
    beliefs: [
      { number: "01", label: "作家", title: "表現の中心に、作家がいる。", body: "知りたいのは絵柄だけでなく、それを描く人のこと。オリジナルのキャラクター、個人的な物語、まだ知られていない世界。その一つひとつが、作品の出発点になります。" },
      { number: "02", label: "限定コレクション", title: "数だけでは語れない価値を。", body: "何度見ても発見のある表現と、作家・テーマ・販売条件がきちんと伝わる作品へ。限定であることを、ひとつの作品に丁寧に向き合うための形と考えています。数量や発売方法は、各コレクションの正式発表時にご案内します。" },
      { number: "03", label: "日常", title: "好きなものと、日々を過ごす。", body: "コレクションは、飾るだけのものではありません。ゲームを始める瞬間も、対戦の合間も、夜更けのデスクでも。手の届くところにある作品が、いつもの時間を少し変えてくれます。" },
    ],
    reynaAlt: "レイナを題材に、キャラクターとアルバムジャケットの構図を探る赤と青のビジュアル研究", creatorVisualNote: "コンセプト研究 / 発売済みコラボ作品ではありません",
    creatorLabel: "03 / 作家の数だけ、世界がある", creatorTitle: ["次の物語は、", "さまざまな作家と。"],
    creatorBody: ["中国各地で活動するイラストレーターや、オリジナル IP を育てるクリエイターとの共創を目指しています。それぞれの個性をコレクションの中心に置き、集める人が自分に響く世界と出会えるように。", "ひとつの作風に揃える必要はありません。鋭く、鮮やかで、少し不思議な世界。あるいは、静かで繊細な世界。私たちが出会いたいのは、その人にしか描けない表現です。"],
    creatorStatus: "作家との共創プロジェクト・準備中", creatorAction: "あなたの作品について聞かせてください", mailSubject: "作家コラボレーションのご相談 / KIKORA",
    objectsLabel: "04 / アートを、触れられるかたちに", objectsTitle: ["ひとつの世界を、", "いろいろなかたちで集める。"], objectsBody: "いま構想しているのは、3つのプロダクト。絵の魅力も、触れた感覚も、使う時間も、作品の一部にしたいと考えています。",
    objects: [
      { href: "/explore/glass", label: "01 / ガラスマウスパッド", title: "ガラスマウスパッド", body: "一枚の絵を、デスクの中心に。", action: "コンセプトを見る" },
      { href: "/explore/keycaps", label: "02 / キーキャップ", title: "アートキーキャップ", body: "キャラクターも色彩も、指先のそばに。", action: "コンセプトを見る" },
      { href: "/explore/metal", label: "03 / メタルカスタム", title: "メタルカスタム", body: "立体の表現へ。集める楽しさを、さらに広く。", action: "構想中のシリーズを見る" },
    ],
    invitationLabel: "物語は、これからも続いていく。", invitationTitle: ["心に響いた世界を、", "いつもそばに。"], invitationBody: ["作家との共創シリーズ、限定コレクションを準備しています。", "次に出会う作家と作品を、一緒に楽しみにしていてください。"], invitationAction: "新作の情報を受け取る",
  },
} as const;
