export const navigationCopy = {
  en: {
    discord: "Join Discord", discordLabel: "Join the KikoraGear Discord community (opens in a new tab)",
    home: "KIKORA home", primary: "Primary navigation", expanded: "Full navigation", glass: "Glass mousepads", keycaps: "Keycaps",
    keycapsCollections: "Keycap collections", keycapsDirections: "KEYCAPS / TWO DIRECTIONS",
    keycapCollections: [
      { id: "set", label: "Keycaps Set", note: "A complete look for your keyboard" },
      { id: "artisan", label: "Artisan Keycaps", note: "Small objects with individual character" },
    ],
    hideKeycaps: "Hide keycap collections", showKeycaps: "Show keycap collections",
    glassCollections: "Glass mousepad collections", glassDirections: "GLASS / THREE DIRECTIONS",
    collections: [
      { id: "core", label: "Core", note: "Material. Surface. Feel." },
      { id: "artist", label: "Artist", note: "Original worlds, individual voices" },
      { id: "covers", label: "Cover series", note: "Where music meets gaming" },
    ],
    openMenu: "Open navigation menu", closeMenu: "Close navigation menu", menu: "Menu", close: "Close", exploreObjects: "EXPLORE THE OBJECTS",
    hideGlass: "Hide glass collections", showGlass: "Show glass collections", story: "Our world", about: "About KIKORA", contact: "Contact", faq: "FAQ", updates: "Edition updates",
    brand: ["Collect your world.", "Independent art. Original IP. Objects to keep."],
    explore: "EXPLORE", information: "INFORMATION", shipping: "Shipping", returns: "Returns", status: "IN DEVELOPMENT",
    invitation: ["Your world.", "Worth collecting."], invitationBody: "Meet the ideas, artists and future editions taking shape at KIKORA.", updatesAction: "Follow new editions",
    copyright: "All rights reserved.", privacy: "Privacy policy", terms: "Terms of service", principles: "ART / IDENTITY / COLLECTION", supportSubject: "KIKORA support request",
  },
  ja: {
    discord: "Discord に参加", discordLabel: "KikoraGear の Discord コミュニティに参加（新しいタブで開きます）",
    home: "KIKORA ホーム", primary: "メインナビゲーション", expanded: "すべてのメニュー", glass: "ガラスマウスパッド", keycaps: "キーキャップ",
    keycapsCollections: "キーキャップのシリーズ", keycapsDirections: "キーキャップから広がる、2つの表現",
    keycapCollections: [
      { id: "set", label: "キーキャップセット", note: "キーボード全体で楽しむデザイン" },
      { id: "artisan", label: "アーティザンキーキャップ", note: "ひとつのキーに宿る個性" },
    ],
    hideKeycaps: "キーキャップのシリーズを閉じる", showKeycaps: "キーキャップのシリーズを開く",
    glassCollections: "ガラスマウスパッドのシリーズ", glassDirections: "ガラスから広がる、3つの表現",
    collections: [
      { id: "core", label: "Core シリーズ", note: "素材と使い心地に向き合う" },
      { id: "artist", label: "Artist シリーズ", note: "それぞれの作家が描く世界" },
      { id: "covers", label: "Cover シリーズ", note: "レコードジャケットからの着想" },
    ],
    openMenu: "メニューを開く", closeMenu: "メニューを閉じる", menu: "メニュー", close: "閉じる", exploreObjects: "作品を探す",
    hideGlass: "ガラスのシリーズを閉じる", showGlass: "ガラスのシリーズを開く", story: "私たちの世界", about: "KIKORA について", contact: "お問い合わせ", faq: "よくあるご質問", updates: "新作のお知らせ",
    brand: ["クリエイターの世界を、あなたのコレクションに。", "アート / オリジナル IP / 日常に置く作品"],
    explore: "作品カテゴリー", information: "ご案内", shipping: "配送について", returns: "返品・交換について", status: "コレクション準備中",
    invitation: ["あなたの世界を、", "手元に。"], invitationBody: "KIKORA で生まれる新しい着想、作家の物語、これからのコレクションをお届けします。", updatesAction: "新作の情報を受け取る",
    copyright: "無断転載を禁じます。", privacy: "プライバシーポリシー", terms: "利用規約", principles: "アート / 個性 / コレクション", supportSubject: "KIKORA お問い合わせ",
  },
} as const;
